Repository Fds17-FinalProject/SweetyPie_Frontend, pull requests merged in 2021-02, with the labels that each got.

#54 리뷰 쓰기 POST 요청 이후 모달창 버그 수정
  src/components/trip/TripCard.jsx
  src/components/trip/TripTemplate.jsx
  src/containers/TripListContainer.js
Labels: feature

#60 헤더 영역 수정
  package-lock.json
  package.json
  public/img/mapIcon.jpg
  src/assets/tailwind.css
  src/components/Main/Header.jsx
  src/components/Main/HeaderLogo.jsx
  src/components/Main/HeaderUser.jsx
  src/components/Main/Main.jsx
  src/components/Main/RegisterModal.jsx
  src/components/Main/userMenu.jsx
  src/components/Modify/ModifyDescription.jsx
  src/components/Search/AccommList.jsx
  src/components/booking/BookingButton.jsx
  src/components/booking/BookingRoomInfo.jsx
  src/components/common/CommonHeader.jsx
  src/components/trip/TripReviewRating.jsx
  src/containers/AuthContainer.js
  src/containers/CommonHeaderContainer.js
  src/containers/MainContainer.js
  src/containers/RegisterContainer.js
  src/pages/MookingPage.js
  src/pages/bookingPage.js
  src/pages/mainPage.js
  src/redux/modules/auth.js
Labels: feature

#77 CalendarDetail 컴포넌트에서 날짜 지우기 및 url 가져오기 기능 구현
  .eslintcache
  public/img/profile_01.jpg
  public/img/profile_02.jpg
  public/img/profile_04.jpg
  src/components/common/Calendar.jsx
  src/components/roomDetail/CalendarDetail.jsx
Labels: feature

#168 지도 렌더링 오류 수정
  src/components/search/AccommList.jsx
  src/components/search/RecentSearch.jsx
  src/components/search/SearchMap.jsx
Labels: bug

#179 달력 컴포넌트 날짜 지우기 에러 수정
  .eslintcache
  src/components/roomDetail/CalendarDetail.jsx
  src/components/roomDetail/Payment.jsx
Labels: bug

#180 Update README.md
  .eslintcache
  README.md
Labels: documentation
